### ISSUE TITLE
traefik as reverse proxy

### ISSUE THREAD

**Issue by stkac** [Monogramm/docker-taiga#17]
Hi, I get this error from taiga-front: need extra config on nginx for use your images? 

thanks in advance,

```
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Start nginx server...
127.0.0.1 - - [26/Apr/2019:12:48:30 +0000] "GET /conf.json HTTP/1.1" 200 855 "-" "curl/7.64.0" "-"
127.0.0.1 - - [26/Apr/2019:12:48:30 +0000] "GET / HTTP/1.1" 200 92007 "-" "curl/7.64.0" "-"
2019/04/26 12:48:30 [error] 30#30: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/v1/ HTTP/1.1", upstream: "http://172.24.0.12:8001/api/v1/", host: "localhost"
127.0.0.1 - - [26/Apr/2019:12:48:30 +0000] "GET /api/v1/ HTTP/1.1" 502 158 "-" "curl/7.64.0" "-"

```

![image](https://user-images.githubusercontent.com/41887474/56809073-49114480-6833-11e9-86e2-ad9ed8fdc273.png)

**Comment by madmath03** [comment]
Hi,

Well, I've never used traefik before so not really gonna be helpful with that, but we've used NGinx as a reverse proxy with those docker images without any issues.

Maybe your proxy addresses are not valid since I see in your logs that your front cannot contact the backend set by `TAIGA_BACK_HOST`:
```
failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/v1/ HTTP/1.1", upstream: "http://172.24.0.12:8001/api/v1/", host: "localhost"
```

Is your traefik setup as a docker container or installed directly on your host ?
If it's a docker container, you can reference services by their container name and inner port, like `taiga_back:8001`.
If it's on the host, you must contact them with their exposed port, like `localhost:18001` if you redirected 8001 to 18001.

Hope that helps a little... Do not hesitate to share more info, like config or compose file, as long as it's not sensitive :wink:

**Comment by madmath03** [comment]
@stkac Any news ?

**Comment by garyritchie** [comment]
@stkac perhaps show us your compose file. It's pretty easy to misconfigure traefik.
