### ISSUE TITLE
Pass TAIGA _SSL=True results nginx error on base front image

### ISSUE THREAD

**Issue by slothyrulez** [Monogramm/docker-taiga#18]
```
- TAIGA_SSL=True
#- TAIGA_SSL_BY_REVERSE_PROXY=True
```
On front and back
Results on nginx error:
```
taiga_taiga_front.1.6l79mzo67new@z1-taiga    | 2019/04/29 06:35:59 [emerg] 29#29: a duplicate default server for 0.0.0.0:80 in /etc/nginx/snippets/main.conf:1                                                                               
taiga_taiga_front.1.6l79mzo67new@z1-taiga    | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/snippets/main.conf:1                                                                                                   
taiga_taiga_front.1.6l79mzo67new@z1-taiga    | nginx: configuration file /etc/nginx/nginx.conf test failed
```
I was triying to mount a external volume to pass the underliying nginx the letsencrypt certifcates 
```
- /etc/letsencrypt/live/mysite:/etc/nginx/ssl:ro
```

**Comment by madmath03** [comment]
Hello @slothyrulez,

Thanks for reporting this issue. I looked a bit in details the SSL mode and found out the error is in the NGINX config which I took from https://github.com/ajira86/docker-taiga : when SSL is enabled, there are 2 server blocks listening to port 80 as default server.

I've only used SSL with Taiga through reverse proxy so I've missed that. My bad.
Fix should be quite easy and available today or tomorrow, depending on DockerHub images build time.

Unrelated but to help you after this has been fixed, be careful on how you mount your letsencrypt certificates : the SSL default conf will expect to find those files `/etc/nginx/ssl/ssl.crt` and `/etc/nginx/ssl/ssl.key` with this exact naming.
Instead of mounting the letsencrypt folder, I suggest you mount certificates directly : 
* `/etc/letsencrypt/live/mysite/cert.pem:/etc/nginx/ssl/ssl.crt:ro`
* `/etc/letsencrypt/live/mysite/privkey.pem:/etc/nginx/ssl/ssl.key:ro`
* `/etc/letsencrypt/archive/mysite:/etc/letsencrypt/archive/mysite:ro` (needed because letsencrypt uses links to certs stored in archive)

**Comment by slothyrulez** [comment]
Thanks for your quick reply @madmath03 !!

> I've only used SSL with Taiga through reverse proxy so I've missed that...

Not sure to fully understand you. 

> Unrelated but to help you after this has been fixed...

Many thanks for the pro tip.

**Comment by madmath03** [comment]
You're welcome 😉 

> > I've only used SSL with Taiga through reverse proxy so I've missed that...

> Not sure to fully understand you.

Well, to put it simply, instead of using `TAIGA_SSL` , we use `TAIGA_SSL_BY_REVERSE_PROXY`.
This means that instead of having taiga_front exposing Taiga directly with SSL, taiga_front will be exposed through simple HTTP and an external reverse proxy will encapsulate the requests with SSL.
