### ISSUE TITLE
Error loading contrib plugins

### ISSUE THREAD

**Issue by karlos1337** [Monogramm/docker-taiga#19]
![imagen](https://user-images.githubusercontent.com/1143362/56882410-c9b68780-6a63-11e9-8422-200a85e76594.png)

I've tried also with 'cookie-warning' plugin with the same result so seems not related to any particular plugin, also have tried `TAIGA_CONTRIB_PLUGINS=gitlab-auth` and `TAIGA_CONTRIB_PLUGINS='gitlab-auth'`, same result.

**Comment by madmath03** [comment]
Hello @karlos1337 ,

The error seems pretty explicit: there is something wrong in one of the json file loaded by Taiga, but I need to know what.

Could you share the content of `http://your.taiga.instance/conf.json`, maybe also `http://your.taiga.instance/plugins/gitlab-auth/gitlab-auth.json` ?

By the way, if you are using docker from command line though, your shell will use the quotes to ensure you a value can have spaces, but if you are using docker-compose to start taiga, you should not use quotes in your environment variables as they will be kept in the final configuration files often making them invalid.

**Comment by karlos1337** [comment]
At this moment we are using swarm to deploy, if can archive a stable taiga with all needed plugins our intention is to use kubernetes, anyway the quotes must not be there as have mentioned so thx :) 

Btw, the correct way to handle that, as is a yaml would be
```
TAIGA_CONTRIB_PLUGINS:
  - gitlab-auth
  - cookie-warning
```
??

Whitescreen in all the app when fill contribPlugins var.

This is the conf.json, using `TAIGA_CONTRIB_PLUGINS=gitlab-auth`
```json
{
    "api": "http://taiga.***.***/api/v1/",
    "eventsUrl": "ws://taiga.***.***/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": false,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga", "material-design", "high-contrast"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": false,
    "feedbackEnabled": true,
    "supportUrl": "https://tree.taiga.io/support",
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "GDPRUrl": null,
    "maxUploadFileSize": 104857600,
    "contribPlugins": ["/plugins/gitlab-auth/gitlab-auth.json"],
    "tribeHost": null,
    "importers": [],
    "gravatar": true,
    "rtlLanguages": ["fa", "he"],
    "loginFormType": "normal"
}
```

the gitlab auth json doesn't load, I think because the js crash on the JSON parse and don't loads anything more and, in the conf.json, the gitlab keys have also dissapear.

**Comment by madmath03** [comment]
Well, you are correct to say that, from the yaml point of view, your syntax would make sense, but I do not know how this syntax would be applied to the environment variable passed to the container...
If it were docker-compose, I'm 100% sure this would not be supported, but I do not know how Kubernetes would handle that... if you try, I would be curious to know the result.

Anyway, regarding your main issue, I'm more concerned by the fact that the other gitlab keys are missing... It almost feels as if you were not using the correct image.

The conf.json that you've posted is perfectly valid, so I'm assuming the error happens when Taiga tries to load the `/plugins/gitlab-auth/gitlab-auth.json` which you mentioned does not load.
My guess is that, somehow, the container image loaded is not the one containing gitlab-auth installed and providing auto config for it.

Is there any trace in the logs of GitLab auto configuration being triggered ?
Could you check which docker image is being loaded for taiga frontend ?

**Comment by karlos1337** [comment]
Working now, seems problem on our side, the container image wasn't updated, now works as charm, thx :)
