### ISSUE TITLE
Gravatars missing (migrating from htdvisser)

### ISSUE THREAD

**Issue by garyritchie** [Monogramm/docker-taiga#26]
Previously I was using htdvisser/taiga-back/front that's around version 3.2 and now I'm looking to update that system to 4.0. I like how you have many of the settings as environment variables. However, setting `- TAIGA_GRAVATAR=true` for taiga front has no effect in my local testing environment.

After some investigation I've found this: https://groups.google.com/forum/#!searchin/taigaio/gravatar|sort:date/taigaio/BmWVToJUTvs/c3ICLIs9BgAJ but I'm not yet certain how to confirm this -- nothing related to gravatar shows up in the logs.

**Comment by madmath03** [comment]
Well, I can confirm you that the Gravatar setting works since I'm using it on several servers, but all those servers have a public IP, so you might be right about the issue you've found.
You can check the gravatar status by accessing `http://my.taiga.instance/conf.json` and make sure the value is set to `true` (which is the default).

I think you will need to ask the question directly to the Taiga team.
