### ISSUE TITLE
Admin login error

### ISSUE THREAD

**Issue by suren2306** [Monogramm/docker-taiga#33]
I launched taiga using the docker-compose file under `images/5.0/alpine`. I am unable to login taiga admin console using the password which I provided in the `.env` file.
The error message found in the browser console is,
```
_error_message: invalid login type
_error_type: taiga.base.exceptions.BadRequest
```
My `.env` file is a follows,
```
[user@taiga alpine]# cat .env 
# Set all your environment variables here


#########################################
## GENERAL
#########################################

HOSTNAME=taiga.test.com
# Adapt to your production domain and use a reverse proxy
#HOSTNAME=taiga.company.com

PORT=80

TAIGA_DB_PWD=password


#########################################
## SECURITY
#########################################

TAIGA_SECRET=MySecretKey

TAIGA_ADMIN_PASSWORD=123123

#########################################
## EMAIL
#########################################

TAIGA_EMAIL_DOMAIN=testdomain.com

TAIGA_SMTP_HOST=XXXXXXXXXXXXXXXXXXXX
TAIGA_SMTP_USER=XXXXXXXXXXXXXXXXXXXX
TAIGA_SMTP_PWD=XXXXXXXXXXXXXXXXXXXXX


#########################################
## GITLAB
#########################################

TAIGA_ENABLE_GITLAB_AUTH=False
#TAIGA_GITLAB_AUTH_URL=https://gitlab.company.com
# Get these from Admin -> Applications
#TAIGA_GITLAB_AUTH_CLIENT_ID=
#TAIGA_GITLAB_AUTH_CLIENT_SECRET=


#########################################
## GITHUB
#########################################

TAIGA_ENABLE_GITHUB_AUTH=False
# Get these from https://github.com/settings/developers
#TAIGA_GITHUB_AUTH_CLIENT_ID=
#TAIGA_GITHUB_AUTH_CLIENT_SECRET=


#########################################
## LDAP
#########################################

TAIGA_ENABLE_LDAP=False
# Adapt to your base domain name
#TAIGA_LDAP_DOMAIN=ldap.company.com
#TAIGA_LDAP_BASE_DN=ou=People,dc=company,dc=com

#TAIGA_LDAP_BIND_DN=
#TAIGA_LDAP_BIND_PASSWORD=

#########################################
## EVENTS
#########################################

TAIGA_RABBIT_USER=taiga
TAIGA_RABBIT_PASSWORD=password
```

**Comment by madmath03** [comment]
Hi @suren2306 ,

Can you please share the logs of your taiga backend container ?

**Comment by suren2306** [comment]
Hi @madmath03 ,

I have set `TAIGA_ENABLE_LDAP=False` in my `.env` file, but by default Taiga is set for LDAP authentication irrespective of the value in the env file. I have fixed the login issue by changing the below parameter in the docker-compose.yml file ( located at docker-taiga/images/5.0/alpine/docker-compose.yml ),
form `- TAIGA_LOGIN_FORM_TYPE=ldap` to ` - TAIGA_LOGIN_FORM_TYPE=normal`

I am not sure is this the right way of doing things, but without changing that I can't able to log in as the admin user.

**Comment by madmath03** [comment]
Hi @suren2306 ,

Yes, this repository docker-compose are setup to use LDAP (and other additional plugins) by default. Changing `TAIGA_LOGIN_FORM_TYPE` to `normal` is the correct way if you do not wish to use LDAP auth.

You initially said though you could not login to the admin console, ie. Django admin console at `http://you.domain/admin` , but since now you're mentioning just a simple login as a user, I guess you only meant to login as the default admin user in Taiga itself.

For information, if LDAP auth is properly configured, it is still possible to login as an internal user by setting `TAIGA_LDAP_FALLBACK` to `normal`.

Anyway, I'm closing this as it was only a misconfiguration of `TAIGA_LOGIN_FORM_TYPE`.
